export const EDIT_CARD = 'EDIT_CARD';
export const EDIT_CARD_CANCEL = 'EDIT_CARD_CANCEL';
export const EDIT_CARD_ACCEPT = 'EDIT_CARD_ACCEPT';
export const DELETE_CARD = 'DELETE_CARD';
export const SET_SETTINGS_MODE = 'SET_SETTINGS_MODE';
export const ADD_NEW_CARDS = 'ADD_NEW_CARDS';